default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["ccblc", "--line-length=120", "--target-version=py37"]

  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
        args: ["-l 88", "-m 2", "ccblc"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
