default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["ccblc", "--line-length=120", "--target-version=py37"]

  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
        args: ["-l 88", "-m2", "ccblc"]

  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        args: ["--select=C,E,F,W,B,B950", "--max-line-length=88", "--ignore=E203,E501,W503,F401,F403", "--exclude=bin,ipython,legacy,plots"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
