name: ccblc

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7.6
  - black
  - earthengine-api
  - flake8
  - folium
  - gdal
  - geopandas
  - ipython
  - isort
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pre-commit
  - psutil
  - pytest
  - pytest-cov
  - rtree
  - shapely
  - pip
  - pip:
    - -r requirements.txt
    - .
